PATTERN_FOLDER = "./z1/pattern"
Z1_TEMP_SVG = "./z1/z1.temp.svg"
Z1_CSS = "./z1/z1.css"

PATTERN_EXT = ".pre.z1"
OUT_SVG_FILE = "out.svg"

BORDER = 20

-- STANDARD PLUGIN
STANDARD_LIGATION_SIZE = 30
STANDARD_DISTANCE_BETWEEN_LIGATIONS = 15
STANDARD_ATOM_RADIUS = 9
STANDARD_WAVES = {
    { 0 },
    {STANDARD_DISTANCE_BETWEEN_LIGATIONS / 2, -STANDARD_DISTANCE_BETWEEN_LIGATIONS / 2},
    {STANDARD_DISTANCE_BETWEEN_LIGATIONS, 0, -STANDARD_DISTANCE_BETWEEN_LIGATIONS}
}

-- ORGANIC PLUGIN
ORGANIC_NO_CARBON_LIGATION_DISTANCE = 6
ORGANIC_CARBON_LIGATION_DISTANCE = 0
ORGANIC_ATOM_RADIUS = 7